export const TRANSLATION_DICTIONARY: Record<string, Record<string, string>> = {
  Tamil: {
    "welcome": "வரவேற்கிறோம்",
    "hello": "வணக்கம்",
    "podcast": "ஒலிபரப்பு",
    "future": "எதிர்காலம்",
    "ai": "செயற்கை நுண்ணறிவு",
    "artificial intelligence": "செயற்கை நுண்ணறிவு",
    "technology": "தொழில்நுட்பம்",
    "voice": "குரல்",
    "voiceover": "குரல்வழி",
    "audio": "ஒலி",
    "episode": "அத்தியாயம்",
    "the": "",
    "of": "இன்",
    "to": "உக்கு",
    "and": "மற்றும்",
    "is": "ஆகும்",
    "your": "உங்கள்",
    "my": "என்",
    "today": "இன்று",
    "show": "நிகழ்ச்சி",
    "education": "கல்வி",
    "learning": "கற்றல்",
    "music": "இசை",
    "science": "அறிவியல்",
    "space": "விண்வெளி",
    "world": "உலகம்",
    "new": "புதிய",
    "good": "நல்ல",
    "morning": "காலை",
    "night": "இரவு",
  },
  Hindi: {
    "welcome": "स्वागत है",
    "hello": "नमस्ते",
    "podcast": "पॉडकास्ट",
    "future": "भविष्य",
    "ai": "एआई",
    "artificial intelligence": "कृत्रिम बुद्धिमत्ता",
    "technology": "तकनीक",
    "voice": "आवाज़",
    "voiceover": "वॉयसओवर",
    "audio": "ऑडियो",
    "episode": "एपिसोड",
    "is": "है",
    "your": "आपका",
    "my": "मेरा",
    "today": "आज",
    "show": "शो",
    "education": "शिक्षा",
    "learning": "सीखना",
    "music": "संगीत",
    "science": "विज्ञान",
    "space": "अंतरिक्ष",
    "world": "दुनिया",
    "new": "नया",
    "good": "अच्छा",
    "morning": "सुबह",
    "night": "रात",
  },
  Telugu: {
    "welcome": "స్వాగతం",
    "hello": "నమస్తే",
    "podcast": "పాడ్‌కాస్ట్",
    "future": "భవిష్యత్తు",
    "ai": "ఎఐ",
    "artificial intelligence": "కృత్రిమ మేధస్సు",
    "technology": "సాంకేతికత",
    "voice": "కంఠస్వరం",
    "voiceover": "వాయిస్‌ఓవర్",
    "audio": "ఆడియో",
    "episode": "ఎపిసోడ్",
    "is": "ఉంది",
    "your": "మీ",
    "my": "నా",
    "today": "ఈరోజు",
    "show": "షో",
    "education": "విద్య",
    "learning": "నేర్చుకోవడం",
    "music": "సంగీతం",
    "science": "విజ్ఞానశాస్త్రం",
    "space": "అంతరిక్షం",
    "world": "ప్రపంచం",
    "new": "కొత్త",
    "good": "మంచి",
    "morning": "ఉదయం",
    "night": "రాత్రి",
  },
  Malayalam: {
    "welcome": "സ്വാഗതം",
    "hello": "ഹലോ",
    "podcast": "പോഡ്‌കാസ്റ്റ്",
    "future": "ഭാവി",
    "ai": "എഐ",
    "artificial intelligence": "കൃത്രിമ ബുദ്ധി",
    "technology": "സാങ്കേതികവിദ്യ",
    "voice": "ശബ്ദം",
    "voiceover": "വോയ്‌സ് ഓവർ",
    "audio": "ഓഡിയോ",
    "episode": "എപ്പിസോഡ്",
    "your": "നിങ്ങളുടെ",
    "my": "എന്റെ",
    "today": "ഇന്ന്",
    "show": "ഷോ",
    "education": "വിദ്യാഭ്യാസം",
    "learning": "പഠനം",
    "music": "സംഗീതം",
    "science": "ശാസ്ത്രം",
    "space": "ബഹിരാകാശം",
    "world": "ലോകം",
    "new": "പുതിയ",
    "good": "നല്ല",
    "morning": "രാവിലെ",
    "night": "രാത്രി",
  },
  Kannada: {
    "welcome": "ಸುಸ್ವಾಗತ",
    "hello": "ನಮಸ್ಕಾರ",
    "podcast": "ಪಾಡ್‌ಕಾಸ್ಟ್",
    "future": "ಭವಿಷ್ಯ",
    "ai": "ಎಐ",
    "artificial intelligence": "ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ",
    "technology": "ತಂತ್ರಜ್ಞಾನ",
    "voice": "ಧ್ವನಿ",
    "voiceover": "ವಾಯ್ಸ್‌ಓವರ್",
    "audio": "ಆಡಿಯೊ",
    "episode": "ಸಂಚಿಕೆ",
    "your": "ನಿಮ್ಮ",
    "my": "ನನ್ನ",
    "today": "ಇಂದು",
    "show": "ಪ್ರದರ್ಶನ",
    "education": "ಶಿಕ್ಷಣ",
    "learning": "ಕಲಿಕೆ",
    "music": "ಸಂಗೀತ",
    "science": "ವಿಜ್ಞಾನ",
    "space": "ಬಾಹ್ಯಾಕಾಶ",
    "world": "ಜಗತ್ತು",
    "new": "ಹೊಸ",
    "good": "ಒಳ್ಳೆಯ",
    "morning": "ಬೆಳಿಗ್ಗೆ",
    "night": "ರಾತ್ರಿ",
  }
};

export const ROMANIZED_DICTIONARY: Record<string, Record<string, string>> = {
  Tamil: {
    "welcome": "varaverkirom",
    "hello": "vanakkam",
    "podcast": "oli-parappu",
    "future": "edhirkalam",
    "ai": "artificial intelligence",
    "artificial intelligence": "artificial intelligence",
    "technology": "thozhil-nutpam",
    "voice": "kural",
    "voiceover": "kural-vazhi",
    "audio": "oli",
    "episode": "adhiyayam",
    "is": "aagum",
    "your": "ungal",
    "my": "en",
    "today": "indru",
    "show": "nighazhchi",
    "education": "kalvi",
    "learning": "katral",
    "music": "isai",
    "science": "ariviyal",
    "space": "vinveli",
    "world": "ulagam",
    "new": "pudhiya",
    "good": "nalla",
    "morning": "kaalai",
    "night": "iravu",
  },
  Hindi: {
    "welcome": "swagat hai",
    "hello": "namaste",
    "podcast": "podcast",
    "future": "bhavishya",
    "ai": "ai",
    "artificial intelligence": "artificial intelligence",
    "technology": "tech",
    "voice": "aawaz",
    "voiceover": "voiceover",
    "audio": "audio",
    "episode": "episode",
    "is": "hai",
    "your": "aapka",
    "my": "mera",
    "today": "aaj",
    "show": "show",
    "education": "shiksha",
    "learning": "seekhna",
    "music": "sangeet",
    "science": "vigyan",
    "space": "antariksh",
    "world": "duniya",
    "new": "naya",
    "good": "achha",
    "morning": "subah",
    "night": "raat",
  },
  Telugu: {
    "welcome": "swagatham",
    "hello": "namaste",
    "podcast": "podcast",
    "future": "bhavishyatthu",
    "ai": "ai",
    "artificial intelligence": "artificial intelligence",
    "technology": "sankethikatha",
    "voice": "kanthaswaram",
    "voiceover": "voiceover",
    "audio": "audio",
    "episode": "episode",
    "is": "undhi",
    "your": "mee",
    "my": "naa",
    "today": "eeroju",
    "show": "show",
    "education": "vidya",
    "learning": "nerchukovadam",
    "music": "sangeetham",
    "science": "vignanasasthram",
    "space": "anthariksham",
    "world": "prapancham",
    "new": "kottha",
    "good": "manchi",
    "morning": "udhayam",
    "night": "rathri",
  },
  Malayalam: {
    "welcome": "swagatham",
    "hello": "hello",
    "podcast": "podcast",
    "future": "bhavi",
    "ai": "ai",
    "artificial intelligence": "artificial intelligence",
    "technology": "sankethika-vidhya",
    "voice": "shabdham",
    "voiceover": "voiceover",
    "audio": "audio",
    "episode": "episode",
    "your": "ningalude",
    "my": "ente",
    "today": "indru",
    "show": "show",
    "education": "vidyabhyasam",
    "learning": "padhanam",
    "music": "sangeetham",
    "science": "shasthram",
    "space": "bahirakasham",
    "world": "lokam",
    "new": "puthiya",
    "good": "nalla",
    "morning": "ravile",
    "night": "rathri",
  },
  Kannada: {
    "welcome": "suswagatha",
    "hello": "namaskara",
    "podcast": "podcast",
    "future": "bhavishya",
    "ai": "ai",
    "artificial intelligence": "artificial intelligence",
    "technology": "thanthra-jnana",
    "voice": "dhwani",
    "voiceover": "voiceover",
    "audio": "audio",
    "episode": "sanchike",
    "your": "nimma",
    "my": "nanna",
    "today": "indhu",
    "show": "show",
    "education": "shikshana",
    "learning": "kalike",
    "music": "sangeetha",
    "science": "vignana",
    "space": "bahyakasha",
    "world": "jagathu",
    "new": "hosa",
    "good": "olleya",
    "morning": "beligge",
    "night": "rathri",
  }
};

export const NATIVE_TEMPLATES: Record<string, string> = {
  Tamil: `வணக்கம்! பாடிஃபை ஒலிபரப்புக்கு உங்களை வரவேற்கிறோம். இன்று நாம் பேசப்போகும் தலைப்பு: "{TITLE}". இதோ உங்கள் ஒலி வடிவம்.`,
  Hindi: `नमस्ते! पॉडीफाई पॉडकास्ट में आपका स्वागत है। आज का हमारा विषय है: "{TITLE}।" पेश है आपकी आवाज़।`,
  Telugu: `నమస్తే! పాడిఫై పాడ్‌కాస్ట్‌కు స్వాగతం. ఈరోజు మన అంశం: "{TITLE}". ఇక్కడ మీ ఆడియో ఉంది.`,
  Malayalam: `നമസ്കാരം! പോഡിഫൈ പോഡ്‌കാസ്റ്റിലേക്ക് സ്വാഗതം. ഇന്നത്തെ വിഷയം: "{TITLE}". ഇതാ നിങ്ങളുടെ ഓഡിയോ.`,
  Kannada: `ನಮಸ್ಕಾರ! ಪೋಡಿಫೈ ಪಾಡ್‌ಕಾಸ್ಟ್‌ಗೆ ಸುಸ್ವಾಗತ. ಇಂದಿನ ವಿಷಯ: "{TITLE}". ನಿಮಗಾಗಿ ಆಡಿಯೊ ಇಲ್ಲಿದೆ.`,
};

export const ROMANIZED_TEMPLATES: Record<string, string> = {
  Tamil: `Vanakkam! Podify oli-parappuku ungalai varaverkirom. Indru naam pesa-pogum thalaippu: "{TITLE}". Idho ungal oli vadivam.`,
  Hindi: `Namaste! Podify podcast mein aapka swagat hai. Aaj ka humara vishay hai: "{TITLE}". Pesh hai aapki aawaz.`,
  Telugu: `Namaste! Podify podcast ku swagatham. Eeroju mana amsam: "{TITLE}". Ikkada mee audio undhi.`,
  Malayalam: `Namaskaram! Podify podcast-ilekku swagatham. Innathe vishayam: "{TITLE}". Itha ningalude audio.`,
  Kannada: `Namaskara! Podify podcast-ge suswagatha. Indhina vishaya: "{TITLE}". Nimagagi audio illide.`,
};

export const getTranslation = (text: string, lang: string, episodeTitle?: string, useRomanized = false) => {
  if (lang === "English" || !text.trim()) return text;

  const hasCharRanges: Record<string, RegExp> = {
    Hindi: /[\u0900-\u097F]/,
    Tamil: /[\u0B80-\u0BFF]/,
    Telugu: /[\u0C00-\u0C7F]/,
    Malayalam: /[\u0D00-\u0D7F]/,
    Kannada: /[\u0C80-\u0CFF]/,
  };

  // If text already contains native characters of the target language, and we aren't forcing Romanized, return text directly!
  if (!useRomanized && hasCharRanges[lang]?.test(text)) {
    return text;
  }

  const dictionary = useRomanized ? ROMANIZED_DICTIONARY[lang] : TRANSLATION_DICTIONARY[lang];
  const templates = useRomanized ? ROMANIZED_TEMPLATES : NATIVE_TEMPLATES;

  if (!dictionary) return text;

  const words = text.toLowerCase().split(/\s+/).filter(Boolean);

  // If the script is very short (e.g. <= 4 words), use the templates as fallback
  if (words.length <= 4) {
    const titleVal = episodeTitle || (useRomanized ? "New Episode" : (lang === "Tamil" ? "புதிய அத்தியாயம்" : lang === "Hindi" ? "नया एपिसोड" : "New Episode"));
    return (templates[lang] || text).replace("{TITLE}", titleVal);
  }

  const translatedWords = words.map(w => {
    const clean = w.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, "");
    return dictionary[clean] || w;
  });

  return translatedWords.join(" ");
};
