// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallbacks ensure the app still boots if env vars weren't injected at build time
// (e.g. on Vercel before the user adds them). These are publishable (anon) keys
// and are safe to expose in client code.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'https://igtfhshkwipawyqvjyul.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndGZoc2hrd2lwYXd5cXZqeXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMTQwMzUsImV4cCI6MjA5Mjg5MDAzNX0.yH1XNhtI_r_FV96bnj3_TGOBJXwpqsW6Eh8ISQcLhng';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
